### ISSUE TITLE
Doesn't work?

### ISSUE THREAD

**Issue by miniluv88** [CursedFlames/NoIncreasingRepairCost#1]
Doesn't work? Repair cost still increases. 
Here's my mods:
- anvilpatch-1.0.0
- fabric-api-0.10.8+build.310-1.15
- litematica-fabric-1.15.2-0.0.0-dev.20200515.184506
- malilib-fabric-1.15.2-0.10.0-dev.21+arne.2
- NoIncreasingRepairCost-1.15.2-1.0.0
- optifabric-1.0.0-beta8
- preview_OptiFine_1.15.2_HD_U_G1_pre18

**Comment by CursedFlames** [comment]
This is a forge mod. No intention of porting to fabric currently.
